services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - 9090:9090
    volumes:
      - ./src/main/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  jaeger:
    image: jaegertracing/jaeger:2.5.0
    ports:
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "16686:16686"
      - "5778:5778"
      - "9411:9411"
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    volumes:
      - ./src/main/docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./src/main/docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
      - jaeger
    