version: '3'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  prometheus:
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - 9090:9090
    volumes:
      - ./src/main/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  tempo:
    image: grafana/tempo
    user: "0:0" # wichtig, da sich der Container sonst nicht starten lässt
    command: 
      - "-config.file"
      - "/etc/tempo.yml"
    ports:
      - "3200:3200" # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
    volumes:
      - ./src/main/docker/tempo/tempo.yml:/etc/tempo.yml
      - tempo-storage:/tmp/tempo/
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./src/main/docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./src/main/docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
      - tempo
volumes:
  grafana-storage: {}
  tempo-storage: {}
    