spring:
    application:
        name: devops-tools
management:
    tracing:
        enabled: true
    endpoints:
        web:
            exposure:
                include: "health,prometheus"
                