logging:
    level:
        io:
            opentelemetry:
                exporter: WARN
spring:
    application:
        name: devops-tools
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
    flyway:
        baseline-on-migrate: false
        out-of-order: false
        validate-on-migrate: true
management:
    endpoints:
        web:
            exposure:
                include: "health,prometheus,env"
otel:
    logs:
        exporter: none
    metrics:
        exporter: none

                