spring:
    application:
        name: devops-tools
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    flyway:
        baseline-on-migrate: false
        out-of-order: false
management:
    tracing:
        enabled: true
    endpoints:
        web:
            exposure:
                include: "health,prometheus,env"
otel:
    logs:
        exporter: none
    metrics:
        exporter: none

                