apiVersion: v1
kind: Secret
metadata:
  name: testsecret
data:
  password: cG9zdGdyZXM=
  spring.datasource.password: cG9zdGdyZXM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testcm
data:
  application-namespace.yaml: |
    spring:
      datasource:
        url: jdbc:postgresql://testpod:5432/postgres
        username: postgres
        password: ${password}
  application-lob.yaml: |
    spring:
      datasource:
        password: postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
  - name: springboot-app
    image: ctsc/devops-tools:latest
    ports:
    - containerPort: 8080
    envFrom:
    - secretRef:
        name: testsecret
    volumeMounts:
    - name: application-config-namespace
      mountPath: /workspace/config/1_namespace
      readOnly: true
    - name: application-config-lob
      mountPath: /workspace/config/2_lob
      readOnly: true
    - name: application-secrets
      mountPath: /workspace/config/3_secrets
      readOnly: true
  - name: postgres-db
    image: postgres:16
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: postgres
    ports:
    - containerPort: 5432
  volumes:
  - name: application-config-namespace
    configMap:
      name: testcm
      items:
        - key: application-namespace.yaml
          path: application.yaml
  - name: application-config-lob
    configMap:
      name: testcm
      items:
        - key: application-lob.yaml
          path: application.yaml
  - name: application-secrets
    secret:
      secretName: testsecret